### ISSUE TITLE
confused to find optimal

### ISSUE THREAD

**Issue by gokhan1987** [Mizogg/Hunting-with-PyQt5#4]
hey there mate. i really appreciate with this work. Its working nice and smooth. however i really wonder what purpose for puzzle.txt, does the software is searching keys for addresses in puzzle.txt folder? does it make sense if i add more address to this folder. there is more than 1 python file, all is working but which one is optimum i couldnt decide. there is folder bit library inside puzzle.txt and qtbit.py i get confused.

**Comment by Mizogg** [comment]
Hi, 

~1000 BTC Bitcoin Challenge Transaction
In 2015, in order to show the hugeness of the private key space (or maybe just for fun), someone created a "puzzle" where he chose keys in a certain smaller space and sent increasing amounts to each of those keys like this:

20 ≤ random key < 21 — 0.001 BTC
21 ≤ random key < 22 — 0.002 BTC
23 ≤ random key < 23 — 0.003 BTC
...
2255 ≤ random key < 2256 — 0.256 BTC
(total 32.896 BTC)

First 65 and #70, #75, #80, #85, #90, #95, #100, #105, #110, #115, #120, #125 private keys have already been cracked.

https://privatekeys.pw/puzzles/bitcoin-puzzle-tx


That is why I include those 160 Addresses. As I can use to find the others or use the found ones for testing the programs. You can add as many address as you like or just 1 to the text file. The more addresses added the slower the scanning as it has to compare more.

Thanks Mizogg
